apiVersion: v1
kind: Service
metadata:
  name: wallet-service
spec:
  selector:
    app: server 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 5000
    nodePort: 31110